/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_input;

import all_classes.FileReadWrite;
import java.awt.Cursor;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class ChangePass extends javax.swing.JFrame {

    /**
     * Creates new form ChangePass
     */
    int mX,mY;
    String Email,Opass,Npass,Cpass;
    public ChangePass() {
        initComponents();
        ImageIcon img=new ImageIcon("img\\cms2.png");
        this.setIconImage(img.getImage());
        try {
            Email=FileReadWrite.FileOutput("files//name");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ChangePass.class.getName()).log(Level.SEVERE, null, ex);
        }
        move.setCursor(new Cursor(Cursor.MOVE_CURSOR));
        exit.setCursor(new Cursor(Cursor.HAND_CURSOR));
        min.setCursor(new Cursor(Cursor.HAND_CURSOR));
        submit.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        move = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        submit = new javax.swing.JLabel();
        alert = new javax.swing.JLabel();
        cpass = new javax.swing.JPasswordField();
        opass = new javax.swing.JPasswordField();
        npass = new javax.swing.JPasswordField();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        move.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moveMouseDragged(evt);
            }
        });
        move.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moveMousePressed(evt);
            }
        });
        getContentPane().add(move, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 418, 20));

        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
        });
        getContentPane().add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 0, 20, 22));

        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 0, 20, 22));

        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 220, 30));

        alert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        alert.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(alert, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 150, 30));

        cpass.setBackground(new java.awt.Color(43, 41, 131));
        cpass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cpass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(cpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 326, 30));

        opass.setBackground(new java.awt.Color(43, 41, 131));
        opass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        opass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(opass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 326, 30));

        npass.setBackground(new java.awt.Color(43, 41, 131));
        npass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        npass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(npass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 326, 30));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/changepass.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void moveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-mX, y-mY);
    }//GEN-LAST:event_moveMouseDragged

    private void moveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveMousePressed
        // TODO add your handling code here:
        mX=evt.getX();
        mY=evt.getY();
    }//GEN-LAST:event_moveMousePressed

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(ChangePass.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
     Opass=opass.getText();
     Npass=npass.getText();
     Cpass=cpass.getText();
     if(Npass.equals(Cpass)){
         try {
             PreparedStatement st = null;
             String sql = "Select * from userinfo WHERE Email=? and Password=?";
             connection();
             st= con.prepareStatement(sql);
             ResultSet res = null;
             //            res = st.executeQuery();
             st.setString(1, Email);
             st.setString(2, Opass);
             //st.setString(4, p2);
             res = st.executeQuery();
             if(res.next())
             {
                 String sql2="Update userinfo set Password='"+Cpass+"' where Email='"+Email+"'";
    
        try{
            Statement st2=null;
            st2=con.createStatement();
            st2.executeUpdate(sql2);
            alert.setText("");
            JOptionPane.showConfirmDialog(this,"Password successfuly changed! ! !.","Confermation message",JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE,new ImageIcon("thik_mark.png"));
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e);
        }
             }
             else{
                 alert.setText("* Password not Match!");
             }
         } catch (SQLException ex) {
             Logger.getLogger(ChangePass.class.getName()).log(Level.SEVERE, null, ex);
         }
     }else{
         alert.setText("* Password not Match!");
     }
    }//GEN-LAST:event_submitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alert;
    private javax.swing.JLabel bg;
    private javax.swing.JPasswordField cpass;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel min;
    private javax.swing.JLabel move;
    private javax.swing.JPasswordField npass;
    private javax.swing.JPasswordField opass;
    private javax.swing.JLabel submit;
    // End of variables declaration//GEN-END:variables
Connection con=null;
    private void connection()
    {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/cms", "root", "");
        }catch(Exception ex){
            
        }
    }

}
