/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_input;
import all_classes.FileReadWrite;
import interface_normal.Help;
import interface_normal.Index;
import java.awt.Cursor;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Forget_password
     */
    int mX,mY;
    Connection con=null;
    public Login() {
        initComponents();
        ImageIcon img=new ImageIcon("img\\pass.png");
        this.setIconImage(img.getImage());
        move.setCursor(new Cursor(Cursor.MOVE_CURSOR));
        exit.setCursor(new Cursor(Cursor.HAND_CURSOR));
        min.setCursor(new Cursor(Cursor.HAND_CURSOR));
        help.setCursor(new Cursor(Cursor.HAND_CURSOR));
        login.setCursor(new Cursor(Cursor.HAND_CURSOR));
        forget.setCursor(new Cursor(Cursor.HAND_CURSOR));
        register.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                exit = new javax.swing.JLabel();
                email = new javax.swing.JTextField();
                pass = new javax.swing.JPasswordField();
                forget = new javax.swing.JLabel();
                register = new javax.swing.JLabel();
                help = new javax.swing.JLabel();
                login = new javax.swing.JLabel();
                min = new javax.swing.JLabel();
                alert = new javax.swing.JLabel();
                move = new javax.swing.JLabel();
                bg = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setBackground(new java.awt.Color(0, 0, 0));
                setUndecorated(true);
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                exit.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                exitMouseClicked(evt);
                        }
                });
                getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 40, 30));

                email.setBackground(new java.awt.Color(27, 82, 89));
                email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                email.setText("Email");
                email.setBorder(null);
                email.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                emailMouseClicked(evt);
                        }
                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                emailMouseExited(evt);
                        }
                });
                getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 102, 308, 36));

                pass.setBackground(new java.awt.Color(27, 82, 89));
                pass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                pass.setText("password");
                pass.setBorder(null);
                pass.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                passMouseClicked(evt);
                        }
                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                passMouseExited(evt);
                        }
                });
                getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 180, 308, 36));

                forget.setBackground(new java.awt.Color(0, 0, 0));
                forget.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                forgetMouseClicked(evt);
                        }
                });
                getContentPane().add(forget, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 160, 40));

                register.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                registerMouseClicked(evt);
                        }
                });
                getContentPane().add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 208, 160, 40));

                help.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                helpMouseClicked(evt);
                        }
                });
                getContentPane().add(help, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 255, 160, 38));

                login.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                loginMouseClicked(evt);
                        }
                });
                getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 120, 40));

                min.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                minMouseClicked(evt);
                        }
                });
                getContentPane().add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 36, 28));

                alert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                alert.setForeground(new java.awt.Color(204, 0, 0));
                getContentPane().add(alert, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 210, 60));
                getContentPane().add(move, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 350, 70));

                bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
                bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                        public void mouseDragged(java.awt.event.MouseEvent evt) {
                                bgMouseDragged(evt);
                        }
                });
                bg.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                bgMousePressed(evt);
                        }
                });
                getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 520, -1));

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void helpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMouseClicked
        // TODO add your handling code here:
//         NewOkCancelDialog nb = new NewOkCancelDialog(new javax.swing.JFrame(), true,"","","","");
//                nb.setVisible(true);
        Help n=new Help();
        n.setVisible(true);
    }//GEN-LAST:event_helpMouseClicked

    private void forgetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetMouseClicked
        // TODO add your handling code here:
        forgetpass n=new forgetpass();
        n.setVisible(true);
    }//GEN-LAST:event_forgetMouseClicked

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        // TODO add your handling code here:
        String Email=email.getText();
        String Password=pass.getText(); 
        try {
            
            PreparedStatement st = null;
            String sql = "Select * from userinfo WHERE Email=? and Password=? and status=?";
            connection();
            st= con.prepareStatement(sql);
            ResultSet res = null;
            //            res = st.executeQuery();          
            st.setString(1, Email);
            st.setString(2, Password);
            st.setString(3, "Active");
            //st.setString(4, p2);
            res = st.executeQuery();
            if(res.next())
            {
                try {
                    FileReadWrite.FileInput(Email,"files//name");
                } catch (IOException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
                if(Email.equalsIgnoreCase("admin")){
                     this.dispose();
                     Index n=new Index();
                     n.setVisible(true);
                }
                else
                {
                    this.dispose();
                    new Index().setVisible(true);
                }
                
            }
            else
            {
                alert.setText("*Email and password not match!!");
                //JOptionPane.showMessageDialog(null,"Email and password is incorrect.\ntry again..");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Db RROR- 404!: try again.the Error is:\n.");
        }  
       
        // main
    }//GEN-LAST:event_loginMouseClicked

    private void emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseClicked
        // TODO add your handling code here:
        if(email.getText().equalsIgnoreCase("Email"))
            email.setText(null);
    }//GEN-LAST:event_emailMouseClicked

    private void passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passMouseClicked
        // TODO add your handling code here:
        if(pass.getText().equalsIgnoreCase("password"))
          pass.setText(null);
    }//GEN-LAST:event_passMouseClicked

    private void emailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseExited

    }//GEN-LAST:event_emailMouseExited

    private void passMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_passMouseExited

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        // TODO add your handling code here:
        Register n=new Register();
        n.setVisible(true);
    }//GEN-LAST:event_registerMouseClicked

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(Login.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-mX, y-mY);
    }//GEN-LAST:event_bgMouseDragged

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        // TODO add your handling code here:
        mX=evt.getX();
        mY=evt.getY();
    }//GEN-LAST:event_bgMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try{
                    //Thread.sleep(5000);
                     new Login().setVisible(true);
                }catch(Exception e)
                {
                    System.out.print(e);
                }
               
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel alert;
        private javax.swing.JLabel bg;
        private javax.swing.JTextField email;
        private javax.swing.JLabel exit;
        private javax.swing.JLabel forget;
        private javax.swing.JLabel help;
        private javax.swing.JLabel login;
        private javax.swing.JLabel min;
        private javax.swing.JLabel move;
        private javax.swing.JPasswordField pass;
        private javax.swing.JLabel register;
        // End of variables declaration//GEN-END:variables

    private void connection()
    {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/cms", "root", "");
        }catch(Exception ex){
            
        }
    }
    //main tag
}
