/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_input;

import all_classes.mailcheck;
import all_classes.mobile;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    int mX,mY;
    Connection con=null;
    public Register() {
        initComponents();
        ImageIcon img=new ImageIcon("img\\signup.png");
        this.setIconImage(img.getImage());
        move.setCursor(new Cursor(Cursor.MOVE_CURSOR));
        exit.setCursor(new Cursor(Cursor.HAND_CURSOR));
        min.setCursor(new Cursor(Cursor.HAND_CURSOR));
        submit.setCursor(new Cursor(Cursor.HAND_CURSOR));
        reset.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        move = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        mob = new javax.swing.JTextField();
        submit = new javax.swing.JLabel();
        reset = new javax.swing.JLabel();
        alert = new javax.swing.JLabel();
        bg_lab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        move.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        move.setForeground(new java.awt.Color(0, 102, 51));
        move.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moveMouseDragged(evt);
            }
        });
        move.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moveMousePressed(evt);
            }
        });
        getContentPane().add(move, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 324, 20));

        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 0, 30, 27));

        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
        });
        getContentPane().add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 21, 30));

        name.setBackground(new java.awt.Color(37, 60, 122));
        name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        name.setToolTipText("Eneter name");
        name.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 68, 208, 27));

        email.setBackground(new java.awt.Color(37, 60, 122));
        email.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        email.setToolTipText("Enter password");
        email.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 122, 206, 27));

        pass.setBackground(new java.awt.Color(37, 60, 122));
        pass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pass.setToolTipText("Enter password");
        pass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 173, 208, 27));

        mob.setBackground(new java.awt.Color(37, 60, 122));
        mob.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mob.setToolTipText("Enter mobile number.Ex: 01681666115");
        mob.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mob.setOpaque(false);
        getContentPane().add(mob, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 222, 208, 25));

        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 100, 20));

        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 100, 20));

        alert.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(alert, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 130, 40));

        bg_lab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user_signup.png"))); // NOI18N
        getContentPane().add(bg_lab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 383, 288));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void moveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-mX, y-mY);
    }//GEN-LAST:event_moveMouseDragged

    private void moveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveMousePressed
        // TODO add your handling code here:
        mX=evt.getX();
        mY=evt.getY();
    }//GEN-LAST:event_moveMousePressed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(Register.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        // TODO add your handling code here:
        if(allValid())
        {
            try {
                con=connection();
                String sql="insert into userinfo(Name,Email,Mobile,Password) values(?,?,?,?)";
                PreparedStatement preparedStatement = con.prepareStatement(sql);
                preparedStatement.setString(1, Name);
                preparedStatement.setString(2, Email);
                preparedStatement.setString(3, Mobile);
                preparedStatement.setString(4, Pass);    
                preparedStatement.executeUpdate();
                JOptionPane.showMessageDialog(null, "Now You are Registerd! But you have to waiting for admin approve!");
                do_null();
            } catch (SQLException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_submitMouseClicked

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
     do_null();
     alert.setText(null);
    }//GEN-LAST:event_resetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alert;
    private javax.swing.JLabel bg_lab;
    private javax.swing.JTextField email;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel min;
    private javax.swing.JTextField mob;
    private javax.swing.JLabel move;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel reset;
    private javax.swing.JLabel submit;
    // End of variables declaration//GEN-END:variables
    String Name,Email,Pass,Mobile;
    private void do_null() {
     name.setText(null);
     email.setText(null);
     pass.setText(null);
     mob.setText(null);
    }

    private boolean allValid() {
        Name=name.getText();
        Email=email.getText();
        Pass=pass.getText();
        Mobile=mob.getText();
        if(Name.equalsIgnoreCase(""))
        {
            alert.setText("* Name not valid");
            //JOptionPane.showMessageDialog(null, "Enter valid Name!");
            return false;
        }
        else if(Email.equalsIgnoreCase("") || mailcheck.checker(Email))
        {
            alert.setText("* Email not valid!");
            //JOptionPane.showMessageDialog(null, "Enter valid Email!");
            return false;
        }
        else if(Pass.equalsIgnoreCase(""))
        {
            alert.setText("* Password not valid");
            //JOptionPane.showMessageDialog(null, "Enter valid Password!");
            return false;
        }
        else if(Mobile.equalsIgnoreCase("") || mobile.checker_no(Mobile))
        {
            alert.setText("* Mobile not valid!");
            //JOptionPane.showMessageDialog(null, "Enter valid Mobile number!");
            return false;
        }
        else{
            alert.setText("");
            return true;
        }
    }
    private Connection connection()
    {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/cms", "root", "");
        }catch(Exception ex){
            
        }
        return con;
    }
}
