/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_output;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Solution_history extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form DetailsBills
     */
    DefaultTableModel model = new DefaultTableModel();
    public Solution_history(java.awt.Frame parent, boolean modal,String cid,String TID,
            String title,String pmsg,String smsg,String sdate,
            String adate,String status,String solver) {
        super(parent, modal);
        initComponents();   
        ImageIcon img=new ImageIcon("img\\cms.png");
        this.setIconImage(img.getImage());
            String a="Client ID : :"+cid;
            Cid.setText(a);
            pid.setText("Problem ID :"+TID);
            Title.setText("Titel : "+title);
            Pmsg.setText(pmsg);
            Smsg.setText(smsg);
            Sdate.setText("Sending Date : "+sdate);
            Adate.setText("Answering Date : "+adate);
            Status.setText("Status : "+status);
            Solver.setText("Solver name : "+solver);
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jButton1 = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();
                jPanel1 = new javax.swing.JPanel();
                pid = new javax.swing.JLabel();
                Cid = new javax.swing.JLabel();
                Title = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                Pmsg = new javax.swing.JTextPane();
                jLabel1 = new javax.swing.JLabel();
                jScrollPane2 = new javax.swing.JScrollPane();
                Smsg = new javax.swing.JTextPane();
                jLabel2 = new javax.swing.JLabel();
                Adate = new javax.swing.JLabel();
                Status = new javax.swing.JLabel();
                Sdate = new javax.swing.JLabel();
                Solver = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();

                setUndecorated(true);
                addWindowListener(new java.awt.event.WindowAdapter() {
                        public void windowClosing(java.awt.event.WindowEvent evt) {
                                closeDialog(evt);
                        }
                });
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jButton1.setText("Print");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });
                getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 50));

                jButton2.setText("Close");
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });
                getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 240, 50));

                jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Problems Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 153, 0))); // NOI18N
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                pid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                pid.setText("pid");
                jPanel1.add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 260, 30));

                Cid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                Cid.setText("cid");
                jPanel1.add(Cid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 230, 30));

                Title.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                Title.setText("Title");
                jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 490, 30));

                Pmsg.setEditable(false);
                Pmsg.setBackground(new java.awt.Color(204, 204, 204));
                Pmsg.setOpaque(false);
                jScrollPane1.setViewportView(Pmsg);

                jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 490, 150));

                jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                jLabel1.setText("Promlems :");
                jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, 20));

                Smsg.setEditable(false);
                Smsg.setBackground(new java.awt.Color(204, 204, 204));
                Smsg.setOpaque(false);
                jScrollPane2.setViewportView(Smsg);

                jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 490, 150));

                jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                jLabel2.setText("Solution :");
                jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 130, 20));

                Adate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                Adate.setText("pid");
                jPanel1.add(Adate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 250, 30));

                Status.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                Status.setText("Title");
                jPanel1.add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 240, 30));

                Sdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                Sdate.setText("cid");
                jPanel1.add(Sdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 240, 30));

                Solver.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                Solver.setText("Promlems :");
                jPanel1.add(Solver, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 240, 30));

                jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                jLabel3.setText("Powered by nullPointerException.");
                jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 580, 250, -1));

                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
                jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 490, 70));

                getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 510, 610));

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog

    }//GEN-LAST:event_closeDialog

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        printJavaComponent();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DetailsBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DetailsBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DetailsBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DetailsBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DetailsBills dialog = new DetailsBills(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel Adate;
        private javax.swing.JLabel Cid;
        private javax.swing.JTextPane Pmsg;
        private javax.swing.JLabel Sdate;
        private javax.swing.JTextPane Smsg;
        private javax.swing.JLabel Solver;
        private javax.swing.JLabel Status;
        private javax.swing.JLabel Title;
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JLabel pid;
        // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
    public void printJavaComponent() {
    PrinterJob job = PrinterJob.getPrinterJob();
    job.setJobName("Print Problems Details!");
 
    job.setPrintable (new Printable() {    
        public int print(Graphics g, PageFormat pageFormat, int pageIndex) {
            if (pageIndex > 0) {
                return(NO_SUCH_PAGE);
            } else {
                Graphics2D g2d = (Graphics2D)g;
                g2d.translate(pageFormat.getImageableX(), 
                pageFormat.getImageableY());
 
                jPanel1.paint(g2d);
                
                return(PAGE_EXISTS); 
            }
        }
    });
         
    if (job.printDialog()) {
        try {
            job.print();
        } catch (PrinterException e) {
            System.err.println(e.getMessage()); 
        }
    }
}
}
