/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_output;

import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ViewBillDetails extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form ViewBillDetails
     */
    int mX,mY;
    DefaultTableModel model = new DefaultTableModel(); 
    String TID;
    public ViewBillDetails(java.awt.Frame parent, boolean modal,String sl) {
        super(parent, modal);
        initComponents();
        ImageIcon img=new ImageIcon("img\\cms.png");
        this.setIconImage(img.getImage());
        move.setCursor(new Cursor(Cursor.MOVE_CURSOR));
        exit.setCursor(new Cursor(Cursor.HAND_CURSOR));
        min.setCursor(new Cursor(Cursor.HAND_CURSOR));
        print.setCursor(new Cursor(Cursor.HAND_CURSOR));
        TID=sl;
        tb_update();
        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        move = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        tid = new javax.swing.JLabel();
        wdate = new javax.swing.JLabel();
        pdate = new javax.swing.JLabel();
        ref = new javax.swing.JLabel();
        cid = new javax.swing.JLabel();
        via = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        print = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        view = new javax.swing.JTable();

        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        move.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moveMouseDragged(evt);
            }
        });
        move.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moveMousePressed(evt);
            }
        });
        getContentPane().add(move, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 30));

        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
        });
        getContentPane().add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 20, 25));

        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 27, 25));
        getContentPane().add(tid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 310, 30));
        getContentPane().add(wdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 250, 30));
        getContentPane().add(pdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 290, 30));
        getContentPane().add(ref, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 300, 30));
        getContentPane().add(cid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 330, 30));
        getContentPane().add(via, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 350, 30));
        getContentPane().add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 310, 30));
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 330, 30));

        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
        });
        getContentPane().add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 170, 40));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pending bill View_1.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 570));

        view.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(view);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 450, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void moveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-mX, y-mY);
    }//GEN-LAST:event_moveMouseDragged

    private void moveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveMousePressed
        // TODO add your handling code here:
        mX=evt.getX();
        mY=evt.getY();
    }//GEN-LAST:event_moveMousePressed

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_minMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked

        MessageFormat head=new MessageFormat(
            "**** Online Transition Details ****"
    );
 model = (DefaultTableModel) view.getModel();

     String a[]={"Client ID          ",cid.getText()};
     String b[]={"Transition         ",TID};
     String c[]={"Which month's bill ",wdate.getText()};
     String d[]={"Paying Date        ",pdate.getText()};
     String e[]={"Reference          ",ref.getText()};
     String f[]={"Amount             ",amount.getText()};
     String g[]={"Via                ",via.getText()};
     String h[]={"Status             ",status.getText()};
     
     model.insertRow(model.getRowCount(), a);
     model.insertRow(model.getRowCount(), b);
     model.insertRow(model.getRowCount(), c);
     model.insertRow(model.getRowCount(), d);
     model.insertRow(model.getRowCount(), e);
     model.insertRow(model.getRowCount(), f);
     model.insertRow(model.getRowCount(), g);
     model.insertRow(model.getRowCount(), h);

     MessageFormat foot=new MessageFormat("Powered By nullPointerException");
     
     try{
         view.print(JTable.PrintMode.NORMAL, head, foot);
         
     }catch(java.awt.print.PrinterException ex)
     {
         JOptionPane.showMessageDialog(null, "Errors:"+ex);
         
     }   
     this.dispose();
    }//GEN-LAST:event_printMouseClicked
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBillDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBillDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBillDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBillDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ViewBillDetails dialog = new ViewBillDetails(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel cid;
    private javax.swing.JLabel exit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel min;
    private javax.swing.JLabel move;
    private javax.swing.JLabel pdate;
    private javax.swing.JLabel print;
    private javax.swing.JLabel ref;
    private javax.swing.JLabel status;
    private javax.swing.JLabel tid;
    private javax.swing.JLabel via;
    private javax.swing.JTable view;
    private javax.swing.JLabel wdate;
    // End of variables declaration//GEN-END:variables
private int returnStatus = RET_CANCEL;
Connection con=null;
    private void connection()
    {
     try{
            Class.forName("com.mysql.jdbc.Driver");
            con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/cms", "root", "");
        }catch(Exception ex){
          
        }
    }
private void tb_update()
    {
 
            try {
                connection();
               // model = (DefaultTableModel) pbills.getModel();          
                PreparedStatement st = null;
                String sql = "Select * from onlinepaybill where tid='"+TID+"'";
            st= con.prepareStatement(sql);
            ResultSet res = null;
            res = st.executeQuery();       
            while(res.next())
            {
              tid.setText(TID);
              cid.setText(res.getString(2));
              wdate.setText(res.getString(3));
              pdate.setText(res.getString(4));
              ref.setText(res.getString(5));
              amount.setText(res.getString(6));
              via.setText(res.getString(7));
              status.setText(res.getString(8));
            }
        }catch(SQLException e)
        {
           System.out.print(e);
        }
    }
}
